type TransportServer
type ProspectiveRoute

exception GeneralFailure ()
exception UnknownMessageID (messageID: MessageID)
exception UnknownTransverseID (transverseID: TransverseID)
exception UnknownReference (reference: Reference)

class Test {
	blah () -> (Int8, Int16, Int32)
}


